spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://jzbjdeal.dbt.djdns.cn:3306/test2?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
    username: qa_user
    password: u9sU4Fo3tSfDHacx
  main:
    allow-circular-references: true

server:
  port: 9091

#mybatis:

mybatis:
  mapper-locations: classpath:mapping/*.xml
  configLocation: classpath:mybatis.xml
#  type-aliases-package: com.onlines.mapper

#project:
#  env: test

logging:
  level:
    org:
      mybatis=DEBUG: