spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: //数据库地址
    username: //数据库账号
    password: //数据库密码
  main:
    allow-circular-references: true

server:
  port: 9090

#mybatis:

mybatis:
  mapper-locations: classpath:mapping/*.xml


project:
  env: publish